name: qftml
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - contourpy
  - cpuonly
  - cryptography
  - cycler
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - expat
  - ffmpeg
  - filelock
  - flit-core
  - fontconfig
  - fonttools
  - freetype
  - giflib
  - glib
  - gmp
  - gmpy2
  - gnutls
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - iniconfig
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab_pygments
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libdeflate
  - libedit
  - libevent
  - libffi
  - libgcc-ng
  - libgomp
  - libiconv
  - libidn2
  - libllvm10
  - libpng
  - libpq
  - libsodium
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - lxml
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numpy
  - numpy-base
  - openh264
  - openssl
  - packaging
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - pluggy
  - ply
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - py
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-fastjsonschema
  - pytorch
  - pytorch-mutex
  - pyzmq
  - qt-main
  - qt-webengine
  - qtwebkit
  - readline
  - requests
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - sympy
  - terminado
  - tinycss2
  - tk
  - toml
  - tomli
  - torchaudio
  - torchvision
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:
      - docopt
      - mpmath
      - nbstripout
      - pipreqs
      - pyqt5-sip
      - yarg
